spring:
  application:
    name: Request Management Project
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/requestdb
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true